global:
  evaluation_interval: 5s
  scrape_interval: 5s

#remote_write:
#- queue_config:
#    capacity: 2500
#    max_samples_per_send: 500
#    max_shards: 6
#  url: http://35.246.201.195:9201/write

scrape_configs:
- job_name: nodeexporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter:9100

- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
